# Build stage for frontend
FROM node:20-alpine AS builder

WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm ci
COPY ./frontend/ .
RUN npm run build

# Nginx stage
FROM docker.io/nginx:1.17.8-alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/nginx.conf